#!groovy
// The above triggers groovy syntax highlighting in vim

plugins {
	id "groovy"
	id "maven-publish"
	id "signing"
	id "application"
	id "me.champeau.jmh" version "0.7.3"
	id "com.vanniktech.maven.publish" version "0.32.0"
}
//https://github.com/melix/jmh-gradle-plugin
jmh {
	includes = ['BenchmarkTest']
	iterations = 3
	warmupIterations = 1
	warmup = '1s'
	jvmArgsAppend = ['-Djava.util.logging.config.file=logging.properties']
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(11)
	}
}

jar {
	manifest {
		attributes(
			'Main-Class' : 'liquibase.Convert2Groovy')
	}
}

application {
	mainClass = 'liquibase.Convert2Groovy'
}

run {
	jvmArgs = ['-Djava.util.logging.config.file=logging.properties']
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

group = "org.liquibase"
archivesBaseName = "liquibase-groovy-dsl"
version = liquibaseGroovyDslVersion

repositories {
	mavenCentral()
	mavenLocal()
}

dependencies {
    String grOrgId = groovyVersion.startsWith("3") ? 'org.codehaus' : 'org.apache'
    implementation "${grOrgId}.groovy:groovy:${groovyVersion}"
    implementation "${grOrgId}.groovy:groovy-sql:${groovyVersion}"

	// This seems redundant, but it isn't.  We need compileOnly so that the main classes will
    // compile, but that dependency doesn't transfer to the unit tests, so we also need
    // testCompile.
	compileOnly "org.liquibase:liquibase-core:${liquibaseVersion}"
	implementation "org.liquibase:liquibase-core:${liquibaseVersion}"
    testImplementation "junit:junit:${junitVersion}"
    testImplementation "org.spockframework:spock-core:2.3-groovy-${groovyVersion[0]}.0"
    testImplementation 'org.junit.vintage:junit-vintage-engine'
    testRuntimeOnly "com.h2database:h2:${h2Version}"
    testRuntimeOnly "ch.qos.logback:logback-classic:${logbackVersion}"
    testRuntimeOnly "info.picocli:picocli:4.7.5"
	testImplementation 'org.openjdk.jmh:jmh-core:1.37'
	jmh 'org.openjdk.jmh:jmh-generator-annprocess:1.37'
	jmh 'org.openjdk.jmh:jmh-generator-bytecode:1.37'
	jmhAnnotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess:1.37'
}

test {
	jvmArgs = ['-Djava.util.logging.config.file=logging.properties']
    useJUnitPlatform()
}

// Configure the Groovy compiler
tasks.withType(GroovyCompile).configureEach {
    // Additional compiler arguments
    groovyOptions.parameters = true // Include parameter names in bytecode (JDK 8+)
}

task sourceJar(type: Jar) {
	description = "An archive of the source code for Maven Central"
    archiveClassifier = "sources"
	from sourceSets.main.allSource
}

task groovydocJar(type: Jar, dependsOn: groovydoc) {
	description = "An archive of the GroovyDocs for Maven Central"
    archiveClassifier = "javadoc"
	from groovydoc
}

// Configure the Vanniktech publishing plugin.
mavenPublishing {
    coordinates(group, archivesBaseName, liquibaseGroovyDslVersion)
    signAllPublications()
    // The vanniktech plugin is supposed to default to Maven Central, but as of 6/21/25, it still
    // defaults to the old OSSRH site.
    publishToMavenCentral(com.vanniktech.maven.publish.SonatypeHost.CENTRAL_PORTAL)
    pom {
        name = "Liquibase Groovy DSL"
        description = "A Groovy-based DSL for the Liquibase database refactoring tool."
        url = "https://github.com/liquibase/liquibase-groovy-dsl"
        licenses {
            license {
                name = "The Apache License, Version 2.0"
                url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                distribution = "http://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        }
        developers {
            developer {
                id = "stevesaliman"
                name = "Steven C. Saliman"
                url = "https://github.com/stevesaliman/"
            }
        }
        scm {
            url = "https://github.com/liquibase/liquibase-groovy-dsl"
            connection = "scm:https://liquibase@github.com/liquibase/liquibase-groovy-dsl"
            developerConnection = "scm:git@github.com:liquibase/liquibase-groovy-dsl.git"
        }
    }
}

