/*
 * Copyright 2011-2024 Tim Berglund and Steven C. Saliman
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package liquibase.parser.ext

import liquibase.changelog.DatabaseChangeLog
import liquibase.database.ObjectQuotingStrategy
import liquibase.resource.ResourceAccessor
import org.liquibase.groovy.delegate.*

import static GroovyLiquibaseChangeLogParser.*
import static groovy.lang.Closure.DELEGATE_ONLY
import static org.liquibase.groovy.delegate.DelegateUtil.objArr

@groovy.transform.TypeChecked
abstract class ParserScript extends Script {

    /** Root element of the <a href='https://docs.liquibase.com/concepts/changelogs/home.html'>changelog</a>
    <br>Params:
    <dl>
    <dt><a href='https://docs.liquibase.com/concepts/changelogs/attributes/logicalfilepath.html'>logicalFilePath</a></dt>
     <dd>Overrides the file name and path when creating the unique identifier of changesets.
     It is required when you want to move or rename changelogs. Default: physical path</dd>
    <dt>{@code contextFilter}</dt>
     <dd>The filter defining which contexts are required the databaseChangeLog to process.
     <a href="https://docs.liquibase.com/concepts/changelogs/attributes/contexts.html">Contexts</a>
     are tags you can add to changesets to control which changesets are executed in any particular migration run.
     Contexts you specify in the databaseChangeLog header are inherited by individual changeSets.
     Renamed from {@code context} since v4.16</dd>
    <dt><a href='https://docs.liquibase.com/concepts/changelogs/attributes/objectquotingstrategy.html'>objectQuotingStrategy</a></dt>
     <dd>Controls how object names are quoted in the SQL files generated by Liquibase and used in calls
     to the database. Default: {@code LEGACY}.</dd>
    </dl>
     */
    void databaseChangeLog( Map<String, Object> args
                           ,String logicalFilePath = null, String contextFilter = null // These are required for mixed parameter calls
                           ,ObjectQuotingStrategy objectQuotingStrategy = null
                           ,@DelegatesTo(value = DatabaseChangeLogDelegate, strategy = DELEGATE_ONLY) Closure closure) {
        // It is required to accept all versions containing named parameter must remain for backward compatibility!!!
        args = argsToMap( args, logicalFilePath, contextFilter, objectQuotingStrategy, closure)
        new DatabaseChangeLogDelegate(getProperty('changeLog') as DatabaseChangeLog,
                                     getProperty('resourceAccessor') as ResourceAccessor, args)
            .call( closure)
    }

    /** Root element of the <a href='https://docs.liquibase.com/concepts/changelogs/home.html'>changelog</a>
     <br>Params:
     <dl>
     <dt><a href='https://docs.liquibase.com/concepts/changelogs/attributes/logicalfilepath.html'>logicalFilePath</a></dt>
         <dd>Overrides the file name and path when creating the unique identifier of changesets.
            It is required when you want to move or rename changelogs. Default: physical path</dd>
     <dt>{@code contextFilter}</dt>
         <dd>The filter defining which contexts are required the databaseChangeLog to process.
             <a href="https://docs.liquibase.com/concepts/changelogs/attributes/contexts.html">Contexts</a>
             are tags you can add to changesets to control which changesets are executed in any particular migration run.
             Contexts you specify in the databaseChangeLog header are inherited by individual changeSets.
             Renamed from {@code context} since v4.16</dd>
     <dt><a href='https://docs.liquibase.com/concepts/changelogs/attributes/objectquotingstrategy.html'>objectQuotingStrategy</a></dt>
        <dd>Controls how object names are quoted in the SQL files generated by Liquibase and used in calls
            to the database. Default: {@code LEGACY}.</dd>
     </dl>
     */
    void databaseChangeLog(String logicalFilePath = null, String contextFilter = null,
                           ObjectQuotingStrategy objectQuotingStrategy = null,
                           @DelegatesTo(value = DatabaseChangeLogDelegate, strategy = DELEGATE_ONLY) Closure closure) {
         databaseChangeLog [:], logicalFilePath, contextFilter, objectQuotingStrategy, closure
    }

    /** Possible method calls with forgotten parameters */
    protected def propertyMissing(String name)  {
        methodMissing( name, objArr())
    }

    /** Handled cases:
        @throw MissingClosure if last parameter is not a required closure
        @throw exception if
     */
    protected Object methodMissing(String name, Object params) {
        if (dbChangeLogTagName != name){
            throw unrecognizedRootElement(name)
        }
        Object[] args = params as Object[]

        // Put the parameters into the map, it must handle all types anyways
        Map map = argsToMap( args)
        Closure cl = args.last() as Closure
        databaseChangeLog( map, cl )
        null
    }

    protected static Map argsToMap(Object... args) {
        Delegatee.argsToMap(null, dbChangeLogTagName, true,
        "(String logicalFilePath, String contextFilter, ObjectQuotingStrategy objectQuotingStrategy) {}",
                ['logicalFilePath', 'contextFilter', 'objectQuotingStrategy', 'cl'], args)
    }
}
